#**Individual Practical Project**
Course: MSc Data Science

Subject: Applied Machine Learning

Cyber Threat Detection Competition Using Machine Learning

AssignmentType: Individual Practical Project

Dataset: Aegean WiFi Intrusion Dataset (AWID)




###**Downloading Dataset**

In [ ]:
# Attempt to make the project reproducible
import random

random.seed(101)
print(random.random())

0.5811521325045647


In [ ]:
#Loading the AWID dataset, adding headers and loading back to disk
import pandas as pd

headername = 'headers_without4and7.csv'
headers = pd.read_csv(headername)

filename = 'train_imperson_without4n7_balanced_data.csv' 
testfilename = 'test_imperson_without4n7_balanced_data.csv'

training = pd.read_csv(filename)
testing = pd.read_csv(testfilename)

training.columns = headers.columns
testing.columns = headers.columns

training.to_csv('train_data_with_headers_without4n7_balanced_data.csv' , sep=',' , index=False)
testing.to_csv('test_data_with_headers_without4n7_balanced_data.csv' , sep=',' , index=False)


In [ ]:
print(training.shape)
training.head()

(97044, 153)


frame.interface_id  frame.dlt  ...  data.len  class
0                   0          0  ...       0.0      0
1                   0          0  ...       0.0      0
2                   0          0  ...       0.0      0
3                   0          0  ...       0.0      0
4                   0          0  ...       0.0      0

[5 rows x 153 columns]

In [ ]:
print(testing.shape)
testing.head()

(40158, 153)


frame.interface_id  frame.dlt  ...  data.len  class
0                   0          0  ...   0.98674      0
1                   0          0  ...   0.98674      0
2                   0          0  ...   0.98674      0
3                   0          0  ...   0.00000      0
4                   0          0  ...   0.98674      0

[5 rows x 153 columns]

In [ ]:
# Divide dataset with and without the target variable

# Dataset without the target variable (so last column has been removed) for training dataset
x_training = training.iloc[:,0:152] 

# Target variable for training dataset
y_training = training.iloc[:,152] 

# Dataset without the target variable (so last column has been removed) for testing dataset
x_testing = testing.iloc[:,0:152]

# Target variable for testing dataset
y_testing = testing.iloc[:,152]

In [ ]:
print(x_training.shape)
x_training.head()

(97044, 152)


frame.interface_id  frame.dlt  ...  wlan.qos.buf_state_indicated.1  data.len
0                   0          0  ...                               0       0.0
1                   0          0  ...                               0       0.0
2                   0          0  ...                               0       0.0
3                   0          0  ...                               0       0.0
4                   0          0  ...                               0       0.0

[5 rows x 152 columns]

In [ ]:
print(x_testing.shape)
x_testing.head()

(40158, 152)


frame.interface_id  frame.dlt  ...  wlan.qos.buf_state_indicated.1  data.len
0                   0          0  ...                               0   0.98674
1                   0          0  ...                               0   0.98674
2                   0          0  ...                               0   0.98674
3                   0          0  ...                               0   0.00000
4                   0          0  ...                               0   0.98674

[5 rows x 152 columns]


###**Constructing and Selecting Features**

####**Feature Extraction using Autoencoder**


In [ ]:
x_training.isnull().any() 

frame.interface_id                False
frame.dlt                         False
frame.offset_shift                False
frame.time_delta                  False
frame.time_delta_displayed        False
                                  ...  
wlan.qos.buf_state_indicated      False
wlan.qos.bit4                     False
wlan.qos.txop_dur_req             False
wlan.qos.buf_state_indicated.1    False
data.len                          False
Length: 152, dtype: bool

In [ ]:
# Rescaling using MinMaxScaler prior to running the Sparse Autoencoders
from sklearn.preprocessing import MinMaxScaler
from numpy import set_printoptions

scaler = MinMaxScaler(feature_range=(0, 1))

x_training = scaler.fit_transform(x_training)
training = pd.DataFrame(x_training, columns = list(training.columns.values)[0:152])

x_testing = scaler.fit_transform(x_testing)
testing= pd.DataFrame(x_training, columns = list(testing.columns.values)[0:152])


In [ ]:
x_training

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
x_testing

array([[0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.98674  ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.98674  ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.98674  ],
       ...,
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.0026525],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.0026525],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.0026525]])

In [ ]:
import numpy as np

# Reshape input as vector
x_training = x_training.reshape((len(x_training), np.prod(x_training.shape[1:])))
x_testing = x_testing.reshape((len(x_testing), np.prod(x_testing.shape[1:])))
print(x_training.shape)
print(x_testing.shape)

(97044, 152)
(40158, 152)


In [ ]:
# Sparse Autoencoders with L1 regularization
import keras
from keras.regularizers import l1 
from keras.optimizers import Adam
from keras.layers import Dense, Input 
import tensorflow as tf

tf.random.set_seed(100)

input_size = 152 
code_size = 20

input = keras.Input(shape=(input_size,))
# Activity regularisation with L1 norm
code = Dense(code_size, activation='relu', activity_regularizer=l1(10e-6))(input) 
output = Dense(input_size, activation='sigmoid')(code)

autoencoder_regularized = keras.Model(input, output) 
autoencoder_regularized.compile(optimizer='adam', loss='binary_crossentropy')
history_regularized = autoencoder_regularized.fit(x_training, x_training, epochs=20)

encoded_regularized = keras.Model(input, code)

Epoch 1/20
3033/3033 [==============================] - 7s 2ms/step - loss: 0.1094
Epoch 2/20
3033/3033 [==============================] - 7s 2ms/step - loss: 0.0303
Epoch 3/20
3033/3033 [==============================] - 6s 2ms/step - loss: 0.0285
Epoch 4/20
3033/3033 [==============================] - 6s 2ms/step - loss: 0.0278
Epoch 5/20
3033/3033 [==============================] - 6s 2ms/step - loss: 0.0276
Epoch 6/20
3033/3033 [==============================] - 6s 2ms/step - loss: 0.0275
Epoch 7/20
3033/3033 [==============================] - 6s 2ms/step - loss: 0.0274
Epoch 8/20
3033/3033 [==============================] - 7s 2ms/step - loss: 0.0274
Epoch 9/20
3033/3033 [==============================] - 7s 2ms/step - loss: 0.0273
Epoch 10/20
3033/3033 [==============================] - 6s 2ms/step - loss: 0.0273
Epoch 11/20
3033/3033 [==============================] - 6s 2ms/step - loss: 0.0273
Epoch 12/20
3033/3033 [==============================] - 6s 2ms/step - loss: 0.0273
E

In [ ]:
x_test_encoded = encoded_regularized.predict(x_testing)

In [ ]:
x_training_encoded = encoded_regularized.predict(x_training)

In [ ]:
x_test_encoded.shape

(40158, 20)

In [ ]:
x_testing.shape

(40158, 152)

In [ ]:
x_training_encoded.shape

(97044, 20)

In [ ]:
x_training.shape

(97044, 152)

####**Combining Original dataset and new extracted features from the autoencoder**



In [ ]:
X_training = np.concatenate((x_training, x_training_encoded), axis = 1)

In [ ]:
X_training.shape

(97044, 172)

In [ ]:
X_testing = np.concatenate((x_testing, x_test_encoded), axis = 1)

In [ ]:
X_testing.shape

(40158, 172)

####**Feature Selection step 1**


In [ ]:
# Checking X_training type prior to selection process
type(X_training)

numpy.ndarray

In [ ]:
X_training.shape

(97044, 172)

In [ ]:
# Changing X_training type from Numpy array to Pandas DataFrame
import pandas as pd

X_training = pd.DataFrame (data=X_training[0:,0:],
                      index= [i for i in range(X_training.shape[0])],
                      columns=[str(i) for i in range (X_training.shape[1])])
X_training.shape

(97044, 172)

In [ ]:
X_training.head()

0    1    2         3  ...       168       169  170       171
0  0.0  0.0  0.0  0.000064  ...  0.000000  0.000000  0.0  3.552652
1  0.0  0.0  0.0  0.000012  ...  0.000000  0.000000  0.0  2.885817
2  0.0  0.0  0.0  0.036308  ...  1.161693  0.405554  0.0  0.000000
3  0.0  0.0  0.0  0.005238  ...  0.745862  1.077770  0.0  0.000000
4  0.0  0.0  0.0  0.035887  ...  1.369457  0.000000  0.0  0.000000

[5 rows x 172 columns]

In [ ]:
type(X_training) 

pandas.core.frame.DataFrame

In [ ]:
type(X_testing)

numpy.ndarray

In [ ]:
# Changing X_testing type from Numpy array to Pandas DataFrame
import pandas as pd

X_testing = pd.DataFrame (data=X_testing[0:,0:],
                      index= [i for i in range(X_testing.shape[0])],
                      columns=['Column '+ str(i) for i in range (X_testing.shape[1])])
X_testing.shape

(40158, 172)

In [ ]:
type(X_testing)

pandas.core.frame.DataFrame

In [ ]:
X_testing.head()

Column 0  Column 1  Column 2  ...  Column 169  Column 170  Column 171
0       0.0       0.0       0.0  ...    2.873188         0.0    0.929745
1       0.0       0.0       0.0  ...    2.885051         0.0    0.769502
2       0.0       0.0       0.0  ...    2.946114         0.0    0.909897
3       0.0       0.0       0.0  ...    0.000000         0.0    2.791876
4       0.0       0.0       0.0  ...    3.347192         0.0    1.573107

[5 rows x 172 columns]

In [ ]:
# Adding header to the combined dataset that include original and extracted features
headername = 'headers_without4and7_withExtractedFeatures.csv'
headers = pd.read_csv(headername)

X_training.columns = headers.columns
X_testing.columns = headers.columns



In [ ]:
X_training.head()

frame.interface_id  frame.dlt  ...  Extracted 19  Extracted 20
0                 0.0        0.0  ...           0.0      3.552652
1                 0.0        0.0  ...           0.0      2.885817
2                 0.0        0.0  ...           0.0      0.000000
3                 0.0        0.0  ...           0.0      0.000000
4                 0.0        0.0  ...           0.0      0.000000

[5 rows x 172 columns]

In [ ]:
X_testing.head()

frame.interface_id  frame.dlt  ...  Extracted 19  Extracted 20
0                 0.0        0.0  ...           0.0      0.929745
1                 0.0        0.0  ...           0.0      0.769502
2                 0.0        0.0  ...           0.0      0.909897
3                 0.0        0.0  ...           0.0      2.791876
4                 0.0        0.0  ...           0.0      1.573107

[5 rows x 172 columns]

In [ ]:
# Saving dataset with combined original and extracted features
X_training.to_csv('full_dataset_training.csv' , sep=',' , index=False)
X_testing.to_csv('full_dataset_testing.csv' , sep=',' , index=False)


Now that he dataset is ready for the feature selection, we can proceed to step 1 of Feature Selection.
The 1st step is to remove all features were 80% of the datapoints have the same value.
Using threshold = 0.8 * (1 - 0.8).
This is motivated by the fact that those features would have low variance thus containing less valuable information for the classification models. 

In [ ]:
from sklearn.feature_selection import VarianceThreshold
random.seed(100)

# Applying VarianceThreshold with get.support function to retain the pandas dataframe format [1].
def Variance_Threshold_DataFrame(data, threshold=(0.16)):
    selector = VarianceThreshold(threshold= (0.16))
    selector.fit(X_training)
    return data[X_training.columns[selector.get_support(indices=True)]]
X_training = Variance_Threshold_DataFrame(X_training, 0.16)


In [ ]:
random_seed = 100
X_training.shape

(97044, 20)

In [ ]:
X_training.head()

radiotap.datarate  radiotap.channel.type.cck  ...  Extracted 18  Extracted 20
0            0.88679                        0.0  ...      0.000000      3.552652
1            0.43396                        0.0  ...      0.000000      2.885817
2            0.00000                        1.0  ...      0.405554      0.000000
3            0.00000                        1.0  ...      1.077770      0.000000
4            0.00000                        1.0  ...      0.000000      0.000000

[5 rows x 20 columns]

Original features columns to keep after VarianceThreshold has ben used:
 6 of the original features can be kept after Variancethreshold has been used.


Extracted Features to keep after using VarianceThreshold:
14 extracted features can be kept after VArianceThreshold has been run


In [ ]:
random_seed = 100
X_training.shape

(97044, 20)

In [ ]:
# Saving X_training dataset after feature selection step 1
X_training.to_csv('dataset_variance_threshold_selection.csv' , sep=',' , index=False)

####**Feature Selection step 2**


In [ ]:
''' Recursive Feature Elimination (RFE class) wrapper method.
This method measures the usefulness of the features based on the classifier performance 
(classifier used here: Logistic Regression) but this is 
computationaly expensive, so the dataset was reduced using VarianceThreshold first. '''


from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
random_seed=100

# feature extraction 
model = LogisticRegression()
rfe = RFE(model, 5)
fit = rfe.fit(X_training, y_training)
print("Num Features: %d" % fit.n_features_)
print("selected Features: %s" % fit.support_)
print("Feature Ranking: %s" % fit.ranking_)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


Num Features: 5
selected Features: [ True  True False False False False False False  True False False False
 False  True False False False False False  True]
Feature Ranking: [ 1  1  3  2 14  6 12  8  1  4 11  9 10  1  7 16 15 13  5  1]


In [ ]:
# X_training = X_training[['wlan.fc.ds','wlan.fc.protected', 'Extracted 10','Extracted 11', 'Extracted 12']]
X_training = X_training[['radiotap.datarate','radiotap.channel.type.cck', 'Extracted 5','Extracted 12', 'Extracted 20']]

print(X_training.shape)
X_training.head()

(97044, 5)


radiotap.datarate  radiotap.channel.type.cck  ...  Extracted 12  Extracted 20
0            0.88679                        0.0  ...      0.696687      3.552652
1            0.43396                        0.0  ...      0.000000      2.885817
2            0.00000                        1.0  ...      1.950850      0.000000
3            0.00000                        1.0  ...      0.591442      0.000000
4            0.00000                        1.0  ...      2.056355      0.000000

[5 rows x 5 columns]

In [ ]:
# Keep the same column from testing dataset
X_testing = X_testing[['radiotap.datarate','radiotap.channel.type.cck', 'Extracted 5','Extracted 12', 'Extracted 20']]

print(X_testing.shape)
X_testing.head()

(40158, 5)


radiotap.datarate  radiotap.channel.type.cck  ...  Extracted 12  Extracted 20
0            1.00000                        0.0  ...      0.788850      0.929745
1            1.00000                        0.0  ...      0.697959      0.769502
2            1.00000                        0.0  ...      0.830441      0.909897
3            0.43396                        0.0  ...      0.023981      2.791876
4            1.00000                        0.0  ...      1.467792      1.573107

[5 rows x 5 columns]


###**Building Machine Learning algorithms for detection task**

ML algorithms that I am going to try

> Logistic Regression as base algorithm
> SVM with linear kernel
> SVM with RBF kernel
> SVM with Polynomial kernel
> SVM with sigmoid kernel



####**Machine Learning Algoritm 1**





In [ ]:
# Logistic Regression as base algorithm
from sklearn.linear_model import LogisticRegression
import sklearn.metrics as metrics

LR = LogisticRegression()
model.LR = LR.fit(X_training, y_training)
predictionsLR = model.LR.predict(X_testing)
CMLogisticRegression = metrics.confusion_matrix(y_testing, predictionsLR)
print(CMLogisticRegression)

[[19603   476]
 [ 2428 17651]]


####**Machine Learning Algorithm 2**

In [ ]:
# SVM with linear kernel
from sklearn.svm import SVC
import sklearn.metrics as metrics

svc = SVC(kernel = 'linear')
modelLinearSVM = svc.fit(X_training, y_training)
predictionsLinearSVM = modelLinearSVM.predict(X_testing)
CMLinearSVM = metrics.confusion_matrix(y_testing, predictionsLinearSVM)
print(CMLinearSVM)

[[19675   404]
 [ 3886 16193]]



####**Machine Learning Algorithm 3**


In [ ]:
# SVM with polynomial kernel
from sklearn.svm import SVC
svc = SVC(kernel = 'poly', degree = 3)
modelPolySVM = svc.fit(X_training, y_training)
predictionsPolySVM = modelPolySVM.predict(X_testing)
CMPolySVM = metrics.confusion_matrix(y_testing, predictionsPolySVM)
print(CMPolySVM)

[[19640   439]
 [ 3997 16082]]


####**Machine Learning Algorithm 4**


In [ ]:
# SVM with RBF kernel (RBF)
from sklearn.svm import SVC
svc = SVC(kernel = 'rbf')
modelRBFSVM = svc.fit(X_training, y_training)
predictionsRBFSVM = modelRBFSVM.predict(X_testing)
CMRBFSVM = metrics.confusion_matrix(y_testing, predictionsRBFSVM)
print(CMRBFSVM)

[[19684   395]
 [ 4668 15411]]


####**Machine Learning Algorithm 5**


In [ ]:
# SVM with Sigmoid Kernel

from sklearn.svm import SVC
svc = SVC(kernel = 'sigmoid')
modelSigSVM = svc.fit(X_training, y_training)
predictionsSigSVM = modelSigSVM.predict(X_testing)
CMSigSVM = metrics.confusion_matrix(y_testing, predictionsRBFSVM)
print(CMSigSVM)

[[19684   395]
 [ 4668 15411]]



###**Evaluating models and Analysing results to select the best models**

In [ ]:
# ML model 1: Logistic Regression Evaluation
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_testing, predictionsLR))
print(classification_report(y_testing, predictionsLR))

[[19603   476]
 [ 2428 17651]]
              precision    recall  f1-score   support

           0       0.89      0.98      0.93     20079
           1       0.97      0.88      0.92     20079

    accuracy                           0.93     40158
   macro avg       0.93      0.93      0.93     40158
weighted avg       0.93      0.93      0.93     40158



In [ ]:
# Calculate mcc for LR
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_testing, predictionsLR)


0.8594421973989401

In [ ]:
# ML mode 2: SVM with Linear kernel Evaluation
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_testing, predictionsLinearSVM))
print(classification_report(y_testing, predictionsLinearSVM))

[[19675   404]
 [ 3886 16193]]
              precision    recall  f1-score   support

           0       0.84      0.98      0.90     20079
           1       0.98      0.81      0.88     20079

    accuracy                           0.89     40158
   macro avg       0.91      0.89      0.89     40158
weighted avg       0.91      0.89      0.89     40158



In [ ]:
# Calculate mcc for SVM Linear kernel
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_testing, predictionsLinearSVM)

0.7984412540769469

In [ ]:
# ML model 3: SVM with polynomial kernel Evaluation
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_testing,predictionsPolySVM))
print(classification_report(y_testing, predictionsPolySVM))

[[19640   439]
 [ 3997 16082]]
              precision    recall  f1-score   support

           0       0.83      0.98      0.90     20079
           1       0.97      0.80      0.88     20079

    accuracy                           0.89     40158
   macro avg       0.90      0.89      0.89     40158
weighted avg       0.90      0.89      0.89     40158



In [ ]:
# Calculate mcc for SVM poly kernel
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_testing, predictionsPolySVM)

0.7915998479283526

In [ ]:
# ML model 4: SVM with RBF kernel Evaluation
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_testing,predictionsRBFSVM))
print(classification_report(y_testing, predictionsRBFSVM))

[[19684   395]
 [ 4668 15411]]
              precision    recall  f1-score   support

           0       0.81      0.98      0.89     20079
           1       0.98      0.77      0.86     20079

    accuracy                           0.87     40158
   macro avg       0.89      0.87      0.87     40158
weighted avg       0.89      0.87      0.87     40158



In [ ]:
# Calculate mcc for SVM rbf kernel
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_testing, predictionsRBFSVM)

0.7653779621885266

In [ ]:
# ML model 5: SVM with Sigmoid Kernel
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_testing,predictionsSigSVM))
print(classification_report(y_testing, predictionsSigSVM))

[[14708  5371]
 [ 1816 18263]]
              precision    recall  f1-score   support

           0       0.89      0.73      0.80     20079
           1       0.77      0.91      0.84     20079

    accuracy                           0.82     40158
   macro avg       0.83      0.82      0.82     40158
weighted avg       0.83      0.82      0.82     40158



In [ ]:
# Calculate mcc for SVM sigmoid kernel
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_testing, predictionsSigSVM)

0.6523701604366937

References:

[1] https://stackoverflow.com/questions/39812885/retain-feature-names-after-scikit-feature-selection
